### ISSUE TITLE
API Documentation view source button leads to 404

### ISSUE THREAD

**Issue by Blooym** [goatcorp/dalamud-docs#1]
All of the "view source" URLs on the API documentation point to `https://github.com/goatcorp/Dalamud.git` so when the URL is generated it leads to something like `https://github.com/goatcorp/Dalamud.git/blob/master/Dalamud/Plugin/DalamudPluginInterface.cs` which isn't a valid URL.

**Comment by avafloww** [comment]
This should be fixed when the latest docbuild completes!

**Comment by alefnull** [comment]
hi, i didn't know if i should create a separate issue for this since it's the same problem - so i thought i'd try just mentioning it here.

all "view source" links on the https://dalamud.dev API documentation are currently also pointing to the repo with ".git" tacked on the end of the repo name, causing all of said links to lead to 404 pages.

**Comment by alefnull** [comment]
adding one more update: i noticed the original issue was fixed (removing the ".git" extension from the repo name), but the links all now point to Dalamud's "main" branch, and Dalamud still appears to use "master" instead of "main", so the links are still pointing to 404 errors.
